<a href="https://colab.research.google.com/github/yoonyoung27/prac_class/blob/main/03_Python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Chapter 2
[Jump to Python Ch2](https://wikidocs.net/11)

###Numeric operations
- Four fundamental arithmatic orperations(+, -, /, *)
- Power(**)
- Quotiant and remainder (%, //)

In [ ]:
3+2

5

In [ ]:
3-2

1

In [ ]:
3/2

1.5

In [ ]:
3*2

6

In [ ]:
3**2

9

In [ ]:
3%2

1

In [ ]:
3//2

1

###String operations
- How to define string("0", '0', """0""", and '''0''')
- Escape codes
- Formating 
- Indexing
- String operations(+,*)
- String functions(join, split, upper, lower, strip, ...)

In [ ]:
str = '''Kevin said "hi Jin"'''
print(str)

Kevin said "hi Jin"


In [ ]:
str = "this is\na string"
print(str)

this is
a string


In [ ]:
a = "40"
"varible a : {}".format(a)

'varible a : 40'

In [ ]:
str = "aabccd"
str[1:3]

'ab'

In [ ]:
str1 = "aab" 
str2 = "ccd"
str1+str2

'aabccd'

In [ ]:
str1*3

'aabaabaab'

In [ ]:
alist = ["a","b","c"]
b = " ".join(alist)
b

'a b c'

In [ ]:
b.split()

['a', 'b', 'c']

In [ ]:
b.upper()

'A B C'

###List
  - How to define a list
  - Indexing
  - List operations (+, *, len )
  - List functions(append, sort, reverse, ...)

In [ ]:
a = [1,2, [1,2], [1,2,[1,2,3]]]
a[3][2][0]

1

In [ ]:
len(a)

4

In [ ]:
b = ['a', 'b', 'c']
a+b

[1, 2, [1, 2], [1, 2, [1, 2, 3]], 'a', 'b', 'c']

In [ ]:
b*3

['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']

In [ ]:
c = [1,2,3,4,0,-1]
c.sort()
c

[-1, 0, 1, 2, 3, 4]

In [ ]:
c.append(10)
c

[-1, 0, 1, 2, 3, 4, 10]

In [ ]:
c.reverse()
c

[10, 4, 3, 2, 1, 0, -1]

###Dictionary
- How to define a dictionary
- Indexing
- Editing
- Dictionary functions(keys, values, items, get(※), in)

In [ ]:
dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
dic['birth']

'1118'

In [ ]:
dic['newkey1'] = 123
dic

{'birth': '1118', 'name': 'pey', 'newkey1': 123, 'phone': '0119993323'}

In [ ]:
dic.keys()

dict_keys(['name', 'phone', 'birth', 'newkey1'])

In [ ]:
dic.values()

dict_values(['pey', '0119993323', '1118', 123])

In [ ]:
dic.items()

dict_items([('name', 'pey'), ('phone', '0119993323'), ('birth', '1118'), ('newkey1', 123)])

In [ ]:
dic.get('name')

'pey'

In [ ]:
dic['namename']

KeyError: ignored

In [ ]:
dic.get('namename')

In [ ]:
'name' in ['name', 'aaa']

True

###\*Chapter 2 practice

1) Remove duplicates
``` python 
>>> a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
```

2) How to extract 'A' and 'B' from the list 'a'?
``` python
>>> a = {'A':90, 'B':80, 'C':70}
```

3) What is the result? 
``` python
>>> a = b = [1, 2, 3]
>>> a[1] = 4
>>> print(b)
```

In [ ]:
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
list(set(a))

[1, 2, 3, 4, 5]

In [ ]:
a = {'A':90, 'B':80, 'C':70}
a['A']

90

In [ ]:
a = b = [1, 2, 3]
a[1] = 4
print(b)

a = [1,2,3]
b = a.copy()
a[1] = 4
print(b)

[1, 4, 3]
[1, 2, 3]


##Chapter 3
[Jump to python ch3](https://wikidocs.net/19)

###If else 

In [ ]:
if 1 :
    print("true")
else :
    print("not true")

if 0 :
    print("true")
else :
    print("not true")

true
not true


In [ ]:
a = 10; b = 0
if a > 0 or b > 2 :
  print("true")
else :
  print("not true")

true


###For loop

In [ ]:
for i in range(5) :
    print(i)

0
1
2
3
4


In [ ]:
listofnames = ['Tom', 'Jane', 'Karl']
for name in listofnames :
    print(name)

Tom
Jane
Karl


In [ ]:
for (key,value) in dic.items() :
    print(key, value)

name pey
phone 0119993323
birth 1118
newkey1 123


###\*Chapter 3 practice 

1) Interprete the code below. What is the result?
``` python
a = "Life is too short, you need python"

if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")
```

2) print numbers 1 to 100 using for loop

3) Do the same thing Using list compression 
``` python
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)
```

In [ ]:
a = "Life is too short, you need python"
 
if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")

shirt


In [ ]:
for i in range(1,101):
    print(i, end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 

In [ ]:
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)
result

[2, 6, 10]

In [ ]:
[n*2 if n%2 == 1 else n*2+1 for n in numbers]

[2, 5, 6, 9, 10]

## Chapter 4 

[Jump to python ch4](https://wikidocs.net/26)

###Function

In [ ]:
def add(a, b):
    return a+b
print(add(3, 4))

7


###Write data

In [ ]:
with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')

In [ ]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')

In [ ]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')

###Read data

In [ ]:
ids = []
with open('ids.txt', 'r') as f :
    for line in f :
        print(line)
        ids.append(line.strip())
ids

ID

John

Karl

Andy

Tim



['ID', 'John', 'Karl', 'Andy', 'Tim']

In [ ]:
ids = []
V1s = []
with open('data1.txt', 'r', encoding='utf-8') as f :
    for item in f :
        print(item)
        ID, field1, _, _ = item.strip().split()
        ids.append(ID)
        V1s.append(field1)
ID
V1s

ID	field1	field2	field3

Tom	1	3	1

John	1	3	3

Tom	1	1	1

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3


['field1', '1', '1', '1', '1', '1', '2', '1']

* split() 메서드는 whitespace를 기반으로 문자열을 나눈다

###Data generator
Do not load all data into the memory. Feed data from file using generator.

In [ ]:
import sys
fnm = 'data2.txt'
def fgenerator(fnm, iter_option = 0) :
    with open(fnm, 'r', encoding='utf-8') as f :
        for idx, item in enumerate(f) :
            ID, V1, V2, V3 = item.strip().split()
            if iter_option == 0 :
                yield ID
            elif iter_option == 1 :
                yield V1
            elif iter_option == 2 :
                yield V2
            else :
                yield V3

gen_from_file = fgenerator(fnm)
for i in gen_from_file :
    print(i)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


* enumerate() 함수를 사용하여 문자열을 반복하면 인덱스와 결과값이 포함된 튜플이 반환된다

In [ ]:
sys.getsizeof(gen_from_file)

128

* sys.getsizeof() 함수는 객체의 메모리 사이즈를 바이트 단위로 반환한다

In [ ]:
def freader(fnm, iter_option = 0) :
    IDs = []
    with open(fnm, 'r', encoding='utf-8') as f :
        for idx, item in enumerate(f) :
            ID, V1, V2, V3 = item.strip().split()
            if iter_option == 0 :
                IDs.append(ID)
            elif iter_option == 1 :
                IDs.append(V1)
            elif iter_option == 2 :
                IDs.append(V2)
            else :
                IDs.append(V3)
    return IDs
res = freader(fnm, 0)
res

['ID',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max']

In [ ]:
sys.getsizeof(res)

200

In [ ]:
class DataGenerator() : 
    def __init__(self, fnm, iter_option=0) :
        self.fnm = fnm
        self.iter_option = iter_option
    
    def __iter__(self) :
        with open(fnm, 'r', encoding='utf-8') as f :
            for idx, item in enumerate(f) :
                ID, V1, V2, V3 = item.strip().split()
                if self.iter_option == 0 :
                    yield ID
                elif self.iter_option == 1 :
                    yield V1
                elif self.iter_option == 2 :
                    yield V2
                else :
                    yield V3
    
    def __len__(self) :
        with open(fnm, 'r', encoding='utf-8') as f :
            for idx, item in enumerate(f) :
                pass
            return idx

fnm = 'data2.txt'
gen1 = DataGenerator(fnm)
for idx, item in enumerate(gen1) :
    print(item)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


* \_\_iter\_\_ 메서드는 해당 객체에 iter()함수를 적용했을 때 호출되는 메서드이다
* \_\_len\_\_ 메서드는 해당 객체에 len()함수를 적용했을 때 호출되는 메서드이다

In [ ]:
list(iter(gen1))

['ID',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max']

In [ ]:
len(gen1)

14

###*Chapter 4 practice
Make a program that produce 'new_data.txt' with IDs listed in ids.txt.

In [ ]:
with open('new_data.txt', 'w') as fw :
    with open("data1.txt", encoding='utf-8') as f:
        for item in f :
            nm, f1, f2, f3 = item.strip().split()
            if nm in ids :
                fw.write(item)

    fw.write("\n")

    with open("data2.txt", encoding='utf-8') as f:
        for item in f :
            nm, f1, f2, f3 = item.strip().split()
        if nm in ids[1:] :
            fw.write(item)

with open("new_data.txt", encoding='utf-8') as f:
    for item in f :
        print(item)

ID	field1	field2	field3

John	1	3	3

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3



####*Pandas 

In [ ]:
import pandas as pd

ids = pd.read_csv('ids.txt', delimiter = "\t")
data1 = pd.read_csv('data1.txt', delimiter = "\t")
data2 = pd.read_csv('data2.txt', delimiter = "\t")

In [ ]:
ids

ID
0  John
1  Karl
2  Andy
3   Tim

In [ ]:
list(ids['ID'])

['John', 'Karl', 'Andy', 'Tim']

In [ ]:
data1

ID  field1  field2  field3
0   Tom       1       3       1
1  John       1       3       3
2   Tom       1       1       1
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3

In [ ]:
data2

ID  field1  field2  field3
0    Tom       2       3       1
1   Jane       1       1       3
2   Jane       2       2       1
3    Max       3       1       2
4   Karl       1       4       2
5    Max       3       2       2
6    Max       2       2       1
7    Tom       2       3       1
8   Jane       1       1       3
9   Jane       2       2       1
10   Max       3       1       2
11  Karl       1       4       2
12   Max       3       2       2
13   Max       2       2       1

In [ ]:
idlist = list(ids['ID'])
filter_d1 = data1['ID'].isin(idlist)
filter_d2 = data2['ID'].isin(idlist)

In [ ]:
data2[filter_d2]

ID  field1  field2  field3
4   Karl       1       4       2
11  Karl       1       4       2

In [ ]:
pd.concat([data1[filter_d1], data2[filter_d2]])

ID  field1  field2  field3
1   John       1       3       3
3   Karl       1       1       2
4   Karl       1       3       2
5   Karl       2       2       2
6   Andy       1       2       3
4   Karl       1       4       2
11  Karl       1       4       2

##Numpy

- NumPy stands for ‘Numerical Python’ or ‘Numeric Python’.

- Provides fast mathematical computation on arrays and matrices

In [2]:
import numpy as np

###Generating

- np.array()
- np.ones()
- np.zeros()
- np.arange()
- np.full()


In [4]:
a = np.array([1,2,3,4,5,0])
b = [1,2,3,4,5]
a + a

array([ 2,  4,  6,  8, 10,  0])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.full([2,3], -1)
a

array([[-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
a.T

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

###Indexing

In [ ]:
a = np.arange(1,10)
a[0:10:2]

array([1, 3, 5, 7, 9])

In [ ]:
b = np.arange(0,10).reshape(2,5)
b[:,2:]

array([[2, 3, 4],
       [7, 8, 9]])

###Operation
* +
* *
* @
* broadcasting

In [ ]:
b + b

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
a * a

array([ 1,  4,  9, 16, 25,  0])

In [ ]:
a @ a #dot product

55

In [7]:
np.array([1,2,3,4]) + np.array([[10,10,10,10],[20,20,20,20]])

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

In [8]:
[1,2,3,4] + [[5,6,7,8],[9,10,11,12]]

[1, 2, 3, 4, [5, 6, 7, 8], [9, 10, 11, 12]]

\* 리스트 연산과 구분

###Function

- np.abs()
- np.exp()
- np.power()
- np.log()
- np.sqrt()


In [ ]:
a = np.arange(-3,5)
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.abs(a)

array([3, 2, 1, 0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01])

In [ ]:
np.power(a,2)

array([ 9,  4,  1,  0,  1,  4,  9, 16])

In [ ]:
np.log(np.array([2,4,8]))

array([0.69314718, 1.38629436, 2.07944154])

In [ ]:
np.log2(np.array([2,4,8]))

array([1., 2., 3.])

In [ ]:
np.log(np.array([3,9])) / np.log(3)

array([1., 2.])

####Statistics 
[Statistics](https://numpy.org/doc/stable/reference/routines.statistics.html)

In [ ]:
np.median(a)

0.5

In [ ]:
np.mean(a)

0.5

In [ ]:
np.std(a)

2.29128784747792

In [9]:
a.prod()

0

\* 모든 원소의 곱

In [10]:
a.argmax()

4

\* max 원소의 위치

In [12]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c.sum(axis=0)

array([ 7,  9, 11, 13, 15])

\* 열을 기준으로 덧셈